version: "3.9"

services:
  app:
    image: ghcr.io/eonseojiancasino/webtest-backend:latest
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: webtest-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./infra/nginx/ssl:/etc/letsencrypt
    restart: unless-stopped
