# application.yml (공통)
spring:
  application:
    name: WebTest
  jackson:
    time-zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true  # 404도 예외로 던지기
  web:
    resources:
      add-mappings: false # 정적 리소스 자동 매핑 끄기
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
# 실행 시 미지정이면 local
---
spring:
  profiles:
    active: local
