global:
  scrape_interval: 15s      # 15초마다 수집
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'webtest-app'
    metrics_path: '/actuator/prometheus'
    scrape_timeout: 10s

    static_configs:
      - targets:
          - 'app:8080'      # ← webtest-app 컨테이너의 서비스 DNS 이름(app) + 포트
