global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'webtest-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webtest-app:8080']
